# 使用官方Python运行时作为父镜像
FROM python:3.9-slim

# 设置工作目录
WORKDIR /app

# 安装必要的包
RUN pip install --no-cache-dir fastapi uvicorn pydantic

# 复制当前目录下的内容到容器内的/app
COPY app/ /app

# 让端口8080在容器外可用
EXPOSE 8080

# 定义环境变量
ENV NAME World
ENV PATH="/app:${PATH}"

# 运行app.py
CMD ["python", "app.py"]

